name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  Deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
      
      # Backend steps
      - name: Install backend dependencies and start test server
        run: |
          cd backend
          npm install
          chmod +x $(npm bin)/ts-node
          npm run start:test &
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Check backend style
        run: |
          cd backend
          chmod +x node_modules/.bin/eslint
          npm run lint
      

      # Frontend steps
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Check frontend style
        run: |
          cd frontend
          npm run lint
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Cypress testing
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run dev
        
      # Deployment backend
      - name: Deploy
        # Only run this step if the branch is main
        if: ${{ github.event_name == 'push' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"